[workspace]
authors = ["Ogarit <tiagomarquesdados@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "alien_invasion"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
